obj-$(CONFIG_DMA_CMA)	+= dma-contiguous.o
obj-$(CONFIG_DMA_SHARED_BUFFER) += dma-buf.o
obj-$(CONFIG_IOMMU_EXYNOS4_API) += s5p-iommu.o
obj-$(CONFIG_SYNC)     += sync.o
obj-$(CONFIG_SW_SYNC)  += sw_sync.o
