obj-$(CONFIG_VIDEO_S5C73M3)    += s5c73m3.o
obj-$(CONFIG_VIDEO_S5C73M3_SPI)        += s5c73m3_spi.o
obj-$(CONFIG_VIDEOBUF2_CMA_PHYS) += videobuf2-cma-phys.o
obj-$(CONFIG_VIDEOBUF2_ION) += videobuf2-ion.o
obj-$(CONFIG_VIDEO_EXYNOS)             += exynos/
obj-$(CONFIG_VIDEO_SAMSUNG)    += samsung/
obj-$(CONFIG_SAMSUNG_MHL)      += mhl/
