obj-$(CONFIG_MMC_MSHCI)		+= mshci.o
obj-$(CONFIG_MMC_MSHCI)		+= mshci-s3c.o
obj-$(CONFIG_MMC_MSHCI_S3C_DMA_MAP)	+= mshci-s3c-dma.o
obj-$(CONFIG_MMC_SDHCI)		+= sdhci.o
obj-$(CONFIG_MMC_SDHCI_S3C)	+= sdhci-s3c.o
