snd-soc-idma-objs := idma.o
snd-soc-dma-wrapper-objs := dma-wrapper.o
snd-soc-audss-objs := audss.o

snd-soc-i2s-objs := i2s.o
obj-$(CONFIG_SND_SAMSUNG_I2S) += snd-soc-i2s.o
obj-$(CONFIG_SND_SAMSUNG_I2S) += snd-soc-idma.o
obj-$(CONFIG_SND_SAMSUNG_I2S) += snd-soc-audss.o
obj-$(CONFIG_SND_SOC_SAMSUNG_USE_DMA_WRAPPER) += snd-soc-dma-wrapper.o

snd-soc-midas-wm1811-objs := midas_wm1811.o
obj-$(CONFIG_SND_SOC_SAMSUNG_MIDAS_WM1811) += snd-soc-midas-wm1811.o
obj-$(CONFIG_SND_SAMSUNG_RP)   += srp_ulp/
obj-$(CONFIG_SND_SAMSUNG_ALP)   += srp_alp/
