ccflags-y += -I$(src)			# needed for trace events

obj-$(CONFIG_ANDROID_BINDER_IPC_LEGACY)		+= binder.o
obj-$(CONFIG_ANDROID_LOGGER_LEGACY)		+= logger.o
obj-$(CONFIG_ANDROID_RAM_CONSOLE_LEGACY)	+= ram_console.o
obj-$(CONFIG_ANDROID_TIMED_OUTPUT_LEGACY)	+= timed_output.o
obj-$(CONFIG_ANDROID_TIMED_GPIO_LEGACY)		+= timed_gpio.o
obj-$(CONFIG_ANDROID_LOW_MEMORY_KILLER_LEGACY)	+= lowmemorykiller.o
obj-$(CONFIG_ANDROID_INTF_ALARM)       += alarm.o
obj-$(CONFIG_ANDROID_INTF_ALARM_DEV)   += alarm-dev.o
