obj-y                         += base/
obj-y                         += gpu/

# Secure OS Mobicore
obj-$(CONFIG_MOBICORE_SUPPORT)  += gud/

obj-y                         += leds/
obj-y                         += media/
obj-$(CONFIG_MMC)             += mmc/
obj-y                         += mfd/
obj-$(CONFIG_POWER_SUPPLY)    += power/
obj-$(CONFIG_FM_RADIO)        += samsung/
obj-$(CONFIG_SENSORS_CORE)    += sensor/
obj-$(CONFIG_THERMAL)         += thermal/
obj-$(CONFIG_USB)             += usb/
obj-$(CONFIG_USB_GADGET)      += usb/
obj-y                         += tty/
