obj-y                         += base/
obj-$(CONFIG_POWER_SUPPLY)    += battery/
obj-y                         += char/
obj-y                         += gpio/
obj-y                         += gpu/

# Secure OS Mobicore
obj-$(CONFIG_MOBICORE_SUPPORT)  += gud/

obj-y                         += i2c/
obj-$(CONFIG_INPUT)           += input/
obj-y                         += leds/
obj-y                         += media/
obj-y                         += mfd/
obj-y                         += misc/
obj-$(CONFIG_VIBETONZ)        += motor/
obj-$(CONFIG_MMC)             += mmc/
obj-y                         += net/
obj-y                         += nfc/
obj-$(CONFIG_POWER_SUPPLY)    += power/
obj-$(CONFIG_REGULATOR)       += regulator/
obj-$(CONFIG_RTC_LIB)         += rtc/
obj-$(CONFIG_FM_RADIO)        += samsung/
obj-$(CONFIG_SENSORS_CORE)    += sensor/
obj-$(CONFIG_SPI)             += spi/
obj-$(CONFIG_SWITCH)          += switch/
obj-$(CONFIG_THERMAL)         += thermal/
obj-y                         += tty/
obj-$(CONFIG_USB)             += usb/
obj-$(CONFIG_USB_GADGET)      += usb/
obj-y                         += video/
