obj-y += testdriver/
obj-y += spi/
obj-$(CONFIG_SPI_S3C64XX) += spi/spi-s3c64xx.o

obj-y += mfd/
obj-$(CONFIG_MIDAS_MFD_MAX77686)    += mfd/max77686.o mfd/max77686-irq.o
obj-$(CONFIG_MIDAS_MFD_MAX77693)    += mfd/max77693.o mfd/max77693-irq.o
obj-$(CONFIG_MIDAS_MFD_WM8994)      += mfd/wm8994-core.o mfd/wm8994-irq.o
